Repository Yash159357/BlyFt, pull requests merged in 2025-09, with the labels that each got.

#276 Added logs in main.dart
  lib/main.dart
Labels: GSSoC

#275 Added logs in Backend Service
  lib/controller/services/backend_service.dart
Labels: GSSoC

#274 Added logs in Theme Service
  lib/controller/services/theme_service.dart
Labels: GSSoC

#269 Implement account deletion
  lib/controller/cubit/user_profile/user_profile_cubit.dart
  lib/controller/services/auth_service.dart
  lib/controller/services/backend_service.dart
  lib/controller/services/firestore_service.dart
  lib/controller/services/reaction_service.dart
  lib/views/inner_screens/settings.dart
  lib/views/nav_screen/home.dart
  server/models/user.js
Labels: GSSoC

#288 Masteryash
  website/contact_us.html
  website/index.html
  website/privacy_policy.html
  website/script.js
  website/style.css
Labels: GSSoC

#294 Add Google OAuth authentication and news API endpoints to documentation
  .github/CONTRIBUTING.md
Labels: gssoc2025, Level 3, hacktoberfest-accepted

#293 Share news feature
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/controller/bloc/bookmark_bloc/bookmark_bloc.dart
  lib/controller/bloc/chat_bloc/chat_bloc.dart
  lib/controller/services/backend_service.dart
  lib/main.dart
  lib/views/auth/signup.dart
  lib/views/inner_screens/shared_news_screen.dart
  lib/views/nav_screen/home.dart
  pubspec.lock
  pubspec.yaml
Labels: gssoc2025, hacktoberfest-accepted
